version: '3.5'
services:
  dbclient:
    image: alpine
    environment:
      - BACKUP_ENABLED=1
      - BACKUP_INTERVAL=3600
      - BACKUP_PATH=/data/db
      - BACKUP_FILENAME=db_backup
      - DB_HOST=db_cluster
      - DB_USER=wpdbuser
      - DB_NAME=wpdb
      - DB_PASSWORD=wpd25245767897965345343bpass
    networks:
      - db_network
    entrypoint: |
      sh -c 'sh -s << EOF
      apk add --no-cache mysql-client
      while true
        do
          if [ $$BACKUP_ENABLED == 1 ]
            then
              sleep $$BACKUP_INTERVAL
              mkdir -p $$BACKUP_PATH/$$(date +%F)
              echo "$$(date +%FT%H.%m) - Making Backup to : $$BACKUP_PATH/$$(date +%F)/$$BACKUP_FILENAME-$$(date +%FT%H.%m).sql.gz"
              mysqldump -u $$DB_USER  -p$$DB_PASSWORD -h $$DB_HOST --all-databases | gzip > $$BACKUP_PATH/$$(date +%F)/$$BACKUP_FILENAME-$$(date +%FT%H.%m).sql.gz
              find $$BACKUP_PATH -mtime 7 -delete
          fi
        done
      EOF'
    volumes:
      - type: bind
        source: /data/db
        target: /data/db
    deploy:
      mode: replicated
      replicas: 1
networks:
  db_network:
    external:
      name: db_network
