version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress
    environment:
      VIRTUAL_HOST: wordpress.euqor.ml
      #      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: wordpress.euqor.ml
      LETSENCRYPT_EMAIL: carlos.laurente@globalip.pe
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassjsajsjasjajajaj
      WORDPRESS_DB_NAME: wpdb
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassjsajsjasjajajaj
      MYSQL_DATABASE: wpdb
    volumes:
      - ./mysql:/var/lib/mysql
